### ISSUE TITLE
It doens't show all directory details

### ISSUE THREAD

**Issue by roeniss** [seligman/dir_sizer#3]
Before starting, I'm thinking that "directory" means actually "prefix" in S3. If it's not, skip the below context and teach me the correct definition, please!

---

In short, `dir_sizer` visualizes only the root directory in my bucket A.

Bucket A has billions of objects and millions of directories, I guess. The total size is not sure but maybe 100 PB I assume. (I found this project because currently all I can do is "assume")

I wonder if this project is not working correctly on recent S3 APIs, or does size matter? I'm not sure what could be wrong.

By the way If this project is not maintained anymore, please let me know. I'll be looking for other one...

**Comment by seligman** [comment]
Your understanding of terms is correct.  dir_sizer started it's life as a tool to visualize local directories, and keeps some of the same terms around for other data sources, even when it's a bit of a misnomer.

Turns out this is simply a bug, it should be fixed with e46f5da4f16f2ed1656ff42a3607a1c5beadea5e , if you can pull it down and give it a shot, please let me know if it fixes the issue for you.

For whatever it's worth, I didn't actually see this since I tend to use AWS Inventory Reports for larger buckets, it's much faster than waiting for S3 to enumerate a bucket, as you'll no doubt see just how painfully long it takes now.

**Comment by roeniss** [comment]
Yeah, actually I've already seen when I use something like `s3 ls`... 😞  

You mean [S3 Inventory](https://docs.aws.amazon.com/AmazonS3/latest/userguide/storage-inventory.html)?

**Comment by seligman** [comment]
Yep, exactly.  A bit annoying to setup, and it'll take a day or so before the report shows up, but for getting information about the contents of large buckets, it's much better than other options, and as a bonus it ends up costing 1/2 or more as just calling ListObjects.

And DirSizer does work with them, I use it out daily on such a large bucket :)

**Comment by roeniss** [comment]
Your story really helps me. Thank you so much
